const constants = {
    CHANGE_MENU: "CHANGE_MENU",
    CHANGE_PAGE: "CAHNGE_PAGE",
    FINISH_LOADING: "FINISH_LOADING",
    CHANGE_TOGGLE: "CHANGE_TOGGLE",
    CHANGE_CONTACT_FORM: "CHANGE_CONTACT_FORM",
    CHANGE_CONTACT_STEP: "CHANGE_CONTACT_STEP",
    RESET_CONTACT_FORM: "RESET_CONTACT_FORM",
    PROGRAM_SET_STEP: "PROGRAM_SET_STEP",
    RESTFUL_API_ADDR: "http://localhost:5000/",
}

export default constants